// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Account
{
    public int Id { get; set; }

    public string Username { get; set; }

    public string PasswordHash { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string ImageAccountUrl { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<AccountRole> AccountRoles { get; set; } = new List<AccountRole>();

    public virtual ICollection<Activity> Activities { get; set; } = new List<Activity>();

    public virtual ICollection<ClubLeaderRequest> ClubLeaderRequestAccounts { get; set; } = new List<ClubLeaderRequest>();

    public virtual ICollection<ClubLeaderRequest> ClubLeaderRequestProcessedByNavigations { get; set; } = new List<ClubLeaderRequest>();

    public virtual ICollection<ClubLeader> ClubLeaders { get; set; } = new List<ClubLeader>();

    public virtual ICollection<MembershipRequest> MembershipRequestAccounts { get; set; } = new List<MembershipRequest>();

    public virtual ICollection<MembershipRequest> MembershipRequestProcessedByNavigations { get; set; } = new List<MembershipRequest>();

    public virtual ICollection<Membership> Memberships { get; set; } = new List<Membership>();
}