// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class ActivityParticipant
{
    public int Id { get; set; }

    public int? ActivityId { get; set; }

    public int? MembershipId { get; set; }

    public int? AccountId { get; set; }

    public DateTime? RegisterTime { get; set; }  // ← THÊM ? (nullable)

    public bool? Attended { get; set; }          // ← THÊM ? (nullable) — nếu DB cho phép NULL

    // Navigation
    public virtual Activity? Activity { get; set; } = null!;

    public virtual Membership? Membership { get; set; }

    public virtual Account? Account { get; set; }
}