// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Activity
{
    public int Id { get; set; }

    public int ClubId { get; set; }

    public string Title { get; set; } = null!;

    public string? Description { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public string? Location { get; set; }

    public string? Status { get; set; }

    public int? CreatedBy { get; set; }

    public string? AvatarPublicId { get; set; }

    public string? ImageActsUrl { get; set; }

    public virtual ICollection<ActivityParticipant> ActivityParticipants { get; set; } = new List<ActivityParticipant>();

    public virtual Club? Club { get; set; }

    public virtual Account? CreatedByNavigation { get; set; }
}