// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class ClubLeaderRequest
{
    public int Id { get; set; }

    public int AccountId { get; set; }

    public DateTime RequestDate { get; set; }

    public string Status { get; set; }

    public int? ProcessedBy { get; set; }

    public DateTime? ProcessedAt { get; set; }

    public string AdminNote { get; set; }

    public string RejectReason { get; set; }

    public string Motivation { get; set; }

    public string Experience { get; set; }

    public string Vision { get; set; }

    public string Commitment { get; set; }

    public virtual Account Account { get; set; }

    public virtual Account ProcessedByNavigation { get; set; }
}