// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class ClubLeader
{
    public int Id { get; set; }

    public int ClubId { get; set; }

    public int AccountId { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public bool? IsActive { get; set; }

    public virtual Account Account { get; set; }

    public virtual Club Club { get; set; }
}