// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Club
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public DateOnly? EstablishedDate { get; set; }

    public string ImageClubsUrl { get; set; }

    public decimal? MembershipFee { get; set; }

    public string Status { get; set; }

    public string AvatarPublicId { get; set; }

    public string Location { get; set; }

    public string ContactEmail { get; set; }

    public string ContactPhone { get; set; }

    public string ActivityFrequency { get; set; }

    public virtual ICollection<Activity> Activities { get; set; } = new List<Activity>();

    public virtual ICollection<ClubLeader> ClubLeaders { get; set; } = new List<ClubLeader>();

    public virtual ICollection<MembershipRequest> MembershipRequests { get; set; } = new List<MembershipRequest>();

    public virtual ICollection<Membership> Memberships { get; set; } = new List<Membership>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();
}