// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class MembershipRequest
{
    public int Id { get; set; }

    public int AccountId { get; set; }

    public int ClubId { get; set; }

    public DateTime RequestDate { get; set; }

    public string Status { get; set; }

    public int? ProcessedBy { get; set; }

    public DateTime? ProcessedAt { get; set; }

    public string Note { get; set; }

    public virtual Account Account { get; set; }

    public virtual Club Club { get; set; }

    public virtual Account ProcessedByNavigation { get; set; }
}