// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Membership
{
    public int Id { get; set; }

    public int AccountId { get; set; }

    public int ClubId { get; set; }

    public DateOnly? JoinDate { get; set; }

    public string Status { get; set; }

    public virtual Account Account { get; set; }

    public virtual ICollection<ActivityParticipant> ActivityParticipants { get; set; } = new List<ActivityParticipant>();

    public virtual Club Club { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();
}