// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Payment
{
    public int Id { get; set; }

    public int? MembershipId { get; set; }

    public int ClubId { get; set; }

    public int AccountId { get; set; }

    public decimal Amount { get; set; }

    public DateTime? PaidDate { get; set; }

    public string? Method { get; set; }

    public string? Status { get; set; }

    public long? OrderCode { get; set; }

    public string? Description { get; set; }

    public virtual Club Club { get; set; } = null!;

    public virtual Membership? Membership { get; set; }

    public virtual Account Account { get; set; } = null!;
}